### PR TITLE
Fix highlighted text scroll jump

### LINKED ISSUE #873: Edit entries: Simplified text auto scrolls after drag and drop
https://recordit.co/Smp51pEwQM

### PR DESCRIPTION
**Pull request by AdityaKhatri**
Fix https://github.com/the-deep/deeper/issues/873

### CODE REVIEW

File: components/View/HighlightedText/index.js [hunk 1]
```diff
@@ -88,6 +90,19 @@ export default class HighlightedText extends React.PureComponent {
...
 
+    componentWillUpdate() {
+        const container = document.getElementsByClassName(styles.highlightedText);
+        this.scrollTop = container ? container[0].scrollTop : undefined;
+    }
+
+    componentDidUpdate() {
+        const container = document.getElementsByClassName(styles.highlightedText);
+
+        if (container && container[0] && this.scrollTop) {
```
Comment (tnagorra) [inline components/View/HighlightedText/index.js]: We should use `isDefined(this.scrollTop)`

File: components/Visualization/VizWrapper/index.js [hunk 2]
```diff
@@ -49,11 +50,14 @@ const propTypes = {
      * Additional css classes for the container/wrapper
      */
     vizContainerClass: PropTypes.string,
+
+    backButton: PropTypes.boolean,
```
Comment (tnagorra) [inline components/Visualization/VizWrapper/index.js]: showBackButton or some other name would be more appropriate for this prop

**Review by tnagorra — CHANGES_REQUESTED** [review]
Need to change prop name

**Review by tnagorra — APPROVED** [review]
